name: Test Monobank

on:
  workflow_dispatch:  # можна запустити вручну

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run test_mono.py
        env:
          MONO_TOKEN: ${{ secrets.MONO_TOKEN }}
        run: python test_mono.py
